# version: '3.8'

# services:
#   mysqldb:
#     image: mysql:5.7
#     restart: unless-stopped
#     env_file: ./.env
#     environment:
#       - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#       - MYSQL_DATABASE=$MYSQLDB_DATABASE
#     ports:
#       - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
#     volumes:
#       - db:/var/lib/mysql
#   app:
#     depends_on:
#       - mysqldb
#     build: ./app
#     restart: unless-stopped
#     env_file: ./.env
#     ports:
#       - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
#     environment:
#       - DB_HOST=mysqldb
#       - DB_USER=$MYSQLDB_USER
#       - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
#       - DB_NAME=$MYSQLDB_DATABASE
#       - DB_PORT=$MYSQLDB_DOCKER_PORT
#     stdin_open: true
#     tty: true

# volumes: 
#   db:



version: "3"

services:
  node:
    image: node:16
    container_name: fooddelivery
    tty: true
    stdin_open: true
    command: bash -c "npm i && npm run dev"
    restart: always
    working_dir: /server
    volumes:
      - ./:/server
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: db

  db:
    container_name: fooddelivery_db
    image: mysql:8.0.21
    restart: always
    ports:
      - 3306:3306
      - 33060:33060
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - ./fooddelivery.sql:/docker-entrypoint-initdb.d/fooddelivery.sql

networks:
  default:
    name: fooddelivery